# tasks to complete before running roles
- hosts: localhost
  connection: local
  become: true

  pre_tasks:

    - name: pre-run | update package cache (arch)
      yum:
        name: '*'
        state: latest
        changed_when: False
      when: ansible_distribution == "Centos"

    - name: re-run | update package cache if older then 3600 seconds (debian, etc)
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: pre-run | update package cache (debian, etc)
      apt:
        force_apt_get: yes
        upgrade: dist
        name: "*"
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
  - name: install packages
    package:
      name:
        - htop

  - name: add ansible user
    user:
      name: ansible.cron
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible.cron
      dest: /etc/sudoers.d/ansible.cron
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible.cron
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/scraane/ansible.git