# tasks to complete before running roles
- hosts: all
  tags: always
  connection: local
  become: true

  pre_tasks:

    - name: pre-run | update package cache (centos)
      dnf:
        name: '*'
        state: latest
        changed_when: False
      when: ansible_distribution in ["Centos", "Rocky"]

    - name: pre-run | install packages
      dnf:
        name: "{{ item }}"
        state: latest
      loop: [ 'htop', 'wget', 'curl', 'vim', 'sudo']  
      when: ansible_distribution in ["Centos", "Rocky"]  

    - name: pre-run | add ansible user
      user:
        name: ansible.cron
        system: yes

    - name: pre-run | set up sudo for ansible user
      copy:
        src: files/sudoer_ansible.cron
        dest: /etc/sudoers.d/ansible.cron
        owner: root
        group: root
        mode: 0440

    - name: pre-run | add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: ansible.cron
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/scraane/ansible.git


- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation

- hosts: server
  tags: server
  become: true
  roles:
    - server

- hosts: docker
  tags: docker
  become: true
  roles:
    - server
    - docker
