---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
   
    - name: Send Telegram message
      telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: "Server needs a reboot: {{ inventory_hostname }}"
          disable_web_page_preview: true
          disable_notification: true
       when: reboot_required_file.stat.exists == true
   
