---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
   
    - name: Send Telegram message when reboot is needed
      telegram:
        token: "{{ notification_telegram_token }}"
        api_args:
          chat_id: "{{ notification_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "Server needs a reboot: {{ inventory_hostname }}"
          disable_web_page_preview: true
          disable_notification: false
      when: reboot_required_file.stat.exists == true

    - name: Sending an e-mail using Legacy SSL to the remote machine
      mail:
        host: "{{ notification_smtp_host }}"
        port: 25
        to: "{{ notification_email_address }}"
        subject: Reboot report
        body: System {{ inventory_hostname }} needs a reboot.
        secure: never
        username: "{{ notification_smtp_username }}"
        password: "{{ notification_smtp_password }}"
