---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
    
    - name: Check if reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
   
    - name: Send Telegram message when reboot is needed
      telegram:
        token: "{{ notification_telegram_token }}"
        api_args:
          chat_id: "{{ notification_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "Server needs a reboot: {{ inventory_hostname }}"
          disable_web_page_preview: true
          disable_notification: false
      when: reboot_required_file.stat.exists == true

    - name: Sending e-mail using {{ notification_smtp_secure }} to {{ notification_smtp_host }}:{{ notification_smtp_port }} when reboot is needed
      mail:
        host: "{{ notification_smtp_host }}"
        port: "{{ notification_smtp_port }}"
        to: "{{ notification_smtp_address }}"
        sender: "{{ notification_smtp_from }}"
        subject: Reboot report
        body: System {{ inventory_hostname }} needs a reboot.
        secure: "{{ notification_smtp_secure }}"
        username: "{{ notification_smtp_username }}"
        password: "{{ notification_smtp_password }}"
      when: reboot_required_file.stat.exists == true
