---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
        
    - name: htop | wget | curl | sudo | neofetch | nala
      apt:
        name: 
          - htop
          - wget
          - curl
          - sudo
          - neofetch
          - nala
        state: present
        update_cache: true
      become: true
      
    - name: base | neofetch | add to motd
      shell: echo "echo" > /etc/profile.d/mymotd.sh && echo "neofetch" >> /etc/profile.d/mymotd.sh && chmod +x /etc/profile.d/mymotd.sh   

    - name: base | nala | add nala fetch to cron
      ansible.builtin.cron:
        name: "nala fetch"
        special_time: "weekly"
        job: "nala fetch --auto -y"
        user: root
      become: true
      
    - name: base | add user | scraane
      user:
        name: "scraane"
        group: "sudo"
        password: "{{ scraane_password | openssl passwd -6}}"
        shell: /bin/bash
        update_password: on_create
        
    - name: Create the .ssh directory
      file:
        path: "~/.ssh"
        state: directory
      become: true
      become_method: sudo
      become_user: "scraane"
      
    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: "scraane"
        state: present
        key: "https://raw.githubusercontent.com/scraane/ansible/master/keys/scraane_id_rsa.pub"

    - name: base | add user | update-user
      user:
        name: "update-user"
        group: "sudo"
        password: "{{ update-user_password | password_hash('sha512')}}"
        shell: /bin/bash
        update_password: on_create
        
    - name: Create the .ssh directory
      file:
        path: "~/.ssh"
        state: directory
      become: true
      become_method: sudo
      become_user: "update-user"
      
    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: "update-user"
        state: present
        key: "https://raw.githubusercontent.com/scraane/ansible/master/keys/update_id_rsa.pub"

  
    - name: Set timezone to Europe/Amsterdam
      timezone:
        name: "Europe/Amsterdam"
     
    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        backup: yes
        # Line to Search/Match against
        regexp: '{{item.From}}'
        # Line to Replace with
        line: '{{item.To}}'
        state: present  
      with_items:
       - { From: '^#Port 22', To: 'Port {{ ssh_port }}'}
       - { From: '^PermitRootLogin yes', To: 'PermitRootLogin no'}
       - { From: '^#PubkeyAuthentication', To: 'PubkeyAuthentication yes'}
       - { From: '^#PasswordAuthentication', To: 'PasswordAuthentication no'}
       - { From: '^#AuthorizedKeysFile', To: 'AuthorizedKeysFile .ssh/authorized_keys'}

    - name: Reboot the machine
      shell: "sleep 5 && reboot"

      async: 1
      poll: 0
