---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
        
    - name: htop | wget | curl | sudo | neofetch
      apt:
        name: 
          - htop
          - wget
          - curl
          - sudo
          - neofetch
        state: present
        update_cache: true
      become: true
      
    - name: base | neofetch | add to motd
      shell: echo "echo" > /etc/profile.d/mymotd.sh && echo "neofetch" >> /etc/profile.d/mymotd.sh && chmod +x /etc/profile.d/mymotd.sh   
      
    - name: base | add user | {{ newuser_username }}
      user:
        name: "{{ newuser_username }}"
        comment: "{{ newuser_comment }}"
        group: "{{ newuser_group }}"
        password: "{{ newuser_password }}"
        shell: /bin/bash
        update_password: on_create
        
    - name: Create the .ssh directory
      file:
        path: "~/.ssh"
        state: directory
      become: true
      become_method: sudo
      become_user: "{{ newuser_username }}"
      
    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: "{{ newuser_username }}"
        state: present
        key: "{{ newuser_pubkey_url }}"
  
    - name: Set timezone to {{ newserver_tz }}
      timezone:
        name: "{{ newserver_tz }}"
     
    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        backup: yes
        # Line to Search/Match against
        regexp: '{{item.From}}'
        # Line to Replace with
        line: '{{item.To}}'
        state: present  
      with_items:
       - { From: '^PermitRootLogin', To: 'PermitRootLogin no'}
       - { From: '^PubkeyAuthentication', To: 'PubkeyAuthentication yes'}
       - { From: '^PasswordAuthentication .*', To: 'PasswordAuthentication no'}
       - { From: '^AuthorizedKeysFile .*', To: 'AuthorizedKeysFile .ssh/authorized_keys'}

    - name: Restart SSH Server
      service:
        name: sshd
        state: restarted
