- name: finalize | reboot | check
  shell: sleep 10 && /sbin/shutdown -r now 'Rebooting box to update system libs/kernel as needed'
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
  when:
    - reboot_required_file.stat.exists
        
- name: finalize | reboot | wait
  wait_for_connection:
    delay: 60
    timeout: 300
    when:
    - reboot_required_file.stat.exists
