- name: duosecurity | install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'duo-unix']

- name: duosecurity | change file permissions
  ansible.builtin.file:
    path: /usr/sbin/login_duo
    owner: scraane
    group: scraane
    mode: '0400'