- name: docker | install
  command: curl -fsSL https://get.docker.com -o get-docker.sh | bash
  
- name: docker | add remote "scraane" user to "docker" group
  remote_user: scraane
  user:
    name: "scraane"
    group: "docker"
    append: yes

- name: docker | create docker-data directory if it does not exist
  file:
    path: /docker_data
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: docker | install docker-compose
  remote_user: scraane
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

#- name: docker | add portainer agent
#  docker_container:
#    name: "portainer-agent"
#   image: "portainer/agent"
#    ports: "9001:9001"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
#    state: started
#    container_default_behavior: no_defaults

- name: docker | copy update.sh script
  copy:
    src: files/update.sh
    dest: /docker-data/update.sh
    mode: a+x
    owner: root
    group: docker
    mode: 0755

- name: docker | create portainer-agent directory if it does not exist
  file:
    path: /docker-data/portainer-agent
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: docker | copy portainer-agent compose script
  copy:
    src: files/portaineragent.yml
    dest: /docker-data/portainer-agent/docker-compose.yml
    mode: a+x
    owner: root
    group: docker
    mode: 0755
    
- name: docker | deploy portainer-agent
  docker_compose:
    project_src: /docker-data/portainer-agent/
    files: /docker-data/portainer-agent/docker-compose.yml
 
