- name: system setup | locale | add nl_NL
  tags: locale,system,setup
  locale_gen:
    name: nl_NL.UTF-8
    state: present

- name: system setup | locale | set locale to nl_NL
  tags: locale,system,setup
  locale_gen:
    name: nl_NL.UTF-8
    state: present
  register: locale

- name: system setup | locale | set nl_NL as default locale
  tags: locale,system,setup
  command: localectl set-locale LANG=nl_NL.UTF-8
  when: locale.changed

- name: system setup | locale | remove en_GB
  tags: locale,system,setup
  locale_gen:
    name: en_GB.UTF-8
    state: absent
  when: locale.changed