- name: base | repositories
 
  block:
    - name: base | repositories | add epel-release
      yum:
        name: epel-release
        state: latest

    - name: base | repositories | add duo-security
      yum_repository:
        name: duo
        description: DUO security YUM repo
        baseurl: https://pkg.duosecurity.com/CentOS/\$releasever/\$basearch