- name: system setup | repositories
 
  block:
    - name: system setup | repositories | add epel-release
      yum:
        name: epel-release
        state: latest
  when: ansible_distribution in ["Centos", "Rocky"]
