---
- hosts: source

  become: yes
  tasks:

    - name: "Comparing {{ ssl_cert_current_location }}/cert.pem with {{ ssl_cert_archive_location }}/cert.pem"
      shell: diff {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}/cert.pem
      register: diff
      failed_when: diff.rc not in [ 0, 1 ]
      
    - name: Setting variable to dummy host for further processing
      add_host:
        name: "variable_holder"
        file_changed:  "{{ diff.rc }}"
    - debug:
        msg: "{{diff.rc}}"
        
    - name: The file has not changed. Ending 1st part of playbook
      meta: end_play
      when: diff.rc == 0

    - name: Remove old compair cert
      file:
        path: /root/ssl_archive/cert.pem
        state: absent

    - name: Copy cert to compare location for next time
      shell: cp {{ ssl_cert_current_location }}/cert.pem /root/ssl_archive/
      register: cp
      failed_when: cp.rc not in [ 0, 1 ]
      when: diff.rc == 1

    - name: Copy content of {{ ssl_cert_current_location }}/privkey.pem to variable
      slurp:
         src: '{{ ssl_cert_current_location }}/privkey.pem'
      register: privkey_pem
      when: diff.rc == 1
      
    - name: Copy content of {{ ssl_cert_current_location }}/fullchain.pem to variable
      slurp:
         src: '{{ ssl_cert_current_location }}/fullchain.pem'
      register: fullchain_pem
      when: diff.rc == 1

    - name: Setting variable to dummy host for further processing
      add_host:
        name: "variable_holder"
        privkey_pem: "{{ privkey_pem.content | b64decode }}"
        fullchain_pem: "{{ fullchain_pem.content | b64decode }}"
      no_log: true
      when: diff.rc == 1
  
- hosts: target

  become: yes

  vars:
    file_changed: "{{ hostvars['variable_holder']['file_changed'] }}"
    
  tasks:
       
    - name: If the file has not changed we will end the playbook
      meta: end_play
      when: file_changed == "0"

    - name: Set the rest of the Vars
      set_fact:
        privkey_pem: "{{ hostvars['variable_holder']['privkey_pem'] }}"
        fullchain_pem: "{{ hostvars['variable_holder']['fullchain_pem'] }}"
      when: file_changed == "1"

    - name: Remove old private key
      file:
        path: "{{ ssl_cert_pve_location }}/pveproxy-ssl.key"
        state: absent

    - name: Remove old fullchain cert
      file:
        path: "{{ ssl_cert_pve_location }}/pveproxy-ssl.pem"
        state: absent
    
    - name: Saving PVE private key
      copy:
        content: "{{ privkey_pem }}"
        dest: "{{ ssl_cert_target_privkey }}"
      when: file_changed == "1"

    - name: Saving PVE fullchain cert
      copy:
        content: "{{ fullchain_pem }}"
        dest: "{{ ssl_cert_target_cert }}"
      when: file_changed == "1"

    - name: Restarting pve proxy
      shell: pveproxy restart
      when: file_changed == "1"
    
    - name: Get PVE Proxy status
      ansible.builtin.systemd:
        name: "{{ service_to_restart }}"
      register: service_status
    
    - debug:
        var: service_status.status.ActiveState
    
    - name: Send Telegram message since certificates are updated
      telegram:
        token: "{{ notification_telegram_token }}"
        api_args:
          chat_id: "{{ notification_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "Certificate updated on: {{ inventory_hostname }}"
          disable_web_page_preview: true
          disable_notification: false
