---
- hosts: source

  become: yes
  tasks:

    - name: Remove old compair cert
      file:
        path: "{{ ssl_cert_archive_location }}"
        state: absent

    - name: Copy cert to compare location for next time
      shell: cp {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}
      register: cp
      failed_when: cp.rc not in [ 0, 1 ]

    - name: Copy content of {{ ssl_cert_current_location }}/privkey.pem to variable
      slurp:
         src: '{{ ssl_cert_current_location }}/privkey.pem'
      register: privkey_pem
      
    - name: Copy content of {{ ssl_cert_current_location }}/fullchain.pem to variable
      slurp:
         src: '{{ ssl_cert_current_location }}/fullchain.pem'
      register: fullchain_pem

    - name: Setting variable to dummy host for further processing
      add_host:
        name: "variable_holder"
        privkey_pem: "{{ privkey_pem.content | b64decode }}"
        fullchain_pem: "{{ fullchain_pem.content | b64decode }}"
      no_log: true
  
- hosts: target

  become: yes

  tasks:

    - name: Set the rest of the Vars
      set_fact:
        privkey_pem: "{{ hostvars['variable_holder']['privkey_pem'] }}"
        fullchain_pem: "{{ hostvars['variable_holder']['fullchain_pem'] }}"

    - name: Saving PVE private key
      copy:
        content: "{{ privkey_pem }}"
        dest: "{{ ssl_cert_target_privkey }}"

    - name: Saving PVE fullchain cert
      copy:
        content: "{{ fullchain_pem }}"
        dest: "{{ ssl_cert_target_cert }}"

    - name: "Restart service {{ service_to_restart }}"
      service:
        name: "{{ service_to_restart }}"
        state: restarted
    
    - name: Get PVE Proxy status
      ansible.builtin.systemd:
        name: "{{ service_to_restart }}"
      register: service_status
    
    - debug:
        var: service_status.status.ActiveState
    
    - name: Send Telegram message since certificates are updated
      telegram:
        token: "{{ notification_telegram_token }}"
        api_args:
          chat_id: "{{ notification_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "Certificate updated on: {{ inventory_hostname }}"
          disable_web_page_preview: true
          disable_notification: false
