---
- hosts: source

  become: yes
  tasks:

    - name: "Comparing {{ ssl_cert_current_location }}/cert.pem with {{ ssl_cert_archive_location }}/cert.pem"
      shell: diff {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}/cert.pem
      register: diff
      failed_when: diff.rc not in [ 0, 1 ]

    - name: "The files have not changed"
      set_fact: 
        file_changed: "false"
      when: diff.rc not in [ 1 ]

    - name: "The files have changed"
      set_fact: 
        file_changed: "true"
      when: diff.rc not in [ 0 ]
      
    - debug:
        var: diff.stdout_lines
    
    - name: add variables to dummy host
      add_host:
        name: "variable_holder"
        shared_variable:  "{{ diff.rc }}"

  
- hosts: target

  become: yes

  vars:
    file_changed: "{{ hostvars['variable_holder']['shared_variable'] }}"
    
  tasks:
    - debug:
        msg: "{{ file_changed }}"
        
    - name: The file has not changed. Ending playbook
      meta: end_play
      when: file_changed == 0
    
    - name: Going through all targets
      shell: "ls"
      when: file_changed == 1
