---
- hosts: source

  become: yes
  tasks:
    
    - name: "Check if ssl cert has been renewed"
      copy:
        src: {{ ssl_cert_current_location }}/cert.pem
        dest: {{ ssl_cert_archive_location }}/cert.pem
      check_mode: yes
      diff: yes
      register: file_changed

    - name: "file has changed"
      shell: "ls"
      when: file_changed == "true"

- hosts: target

  become: yes
  tasks:
    - name: Going through all targets
      shell: "ls"
      when: file_changed == "true"
