---
- hosts: source

  become: yes
  tasks:
    
    - name: Check if ssl cert "{{ ssl_cert_current_location }}"/cert.pem has been renewed 
      copy:
        src: "{{ ssl_cert_current_location }}/cert.pem"
        dest: "{{ ssl_cert_archive_location }}/cert.pem"
      check_mode: yes
      diff: yes
      register: file_changed
      msg: file_changed

    - name: "file has changed"
      when: file_changed == "true"

- hosts: target

  become: yes
  tasks:
    - name: Going through all targets
      when: file_changed == "true"
