---
- hosts: source

  become: yes
  tasks:

    - name: "Comparing {{ ssl_cert_current_location }}/cert.pem with {{ ssl_cert_archive_location }}/cert.pem"
      shell: diff {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}/cert.pem
      register: diff
      failed_when: diff.rc not in [ 0, 1 ]

    - name: The file has not changed. Ending 1st part of playbook
      meta: end_play
      when: diff.rc == 0

    - name: Setting variable to dummy host for further processing
      add_host:
        name: "variable_holder"
        file_changed:  "{{ diff.rc }}"

    - name: Copy content of {{ item.File }} to variable
      slurp:
         src: '{{ item.File }}'
      register: "{{ item.Var }}"
      with_items:
        - {Var:'cert_pem', File: '{{ ssl_cert_current_location }}/cert.pem'}
        - {Var:'privkey_pem', File: '{{ ssl_cert_current_location }}/privkey.pem'}
        - {Var:'chain_pem', File: '{{ ssl_cert_current_location }}/chain.pem'}
        - {Var:'fullchain_pem', File: '{{ ssl_cert_current_location }}/fullchain.pem'}
      when: diff.rc == 1

    - name: Setting variable to dummy host for further processing
      add_host:
        name: "variable_holder"
        "{{ item.Var }}":  "{{ item.Content }}"
      with_items:
        - { Var: 'cert_pem', Content: '{{ cert_pem.content | b64decode }}'}
        - { Var: 'privkey_pem', Content: '{{ privkey_pem.content | b64decode }}'}
        - { Var: 'chain_pem', Content: '{{ chain_pem.content | b64decode }}'}
        - { Var: 'fullchain_pem', Content: '{{ fullchain_pem.content | b64decode }}'}
      when: diff.rc == 1

  
- hosts: target

  become: yes

  vars:
    file_changed: "{{ hostvars['variable_holder']['file_changed'] }}"
    cert_pem: "{{ hostvars['variable_holder']['cert_pem'] }}"
    
  tasks:
    - debug:
        msg: "{{ file_changed }}"
        
    - name: The file has not changed. Ending playbook
      meta: end_play
      when: file_changed == "0"
    
    - name: Going through all targets
      shell: "ls"
      when: file_changed == "1"
