---
- hosts: source

  become: yes
  tasks:

  - name: "register the first file {{ ssl_cert_current_location }}/cert.pem"
    stat:
      path: "{{ ssl_cert_archive_location }}/cert.pem"
      checksum: sha1
      get_checksum: yes
    register: file_1
  
  - name: "register the second file {{ ssl_cert_archive_location }}/cert.pem"
    stat:
      path: "{{ ssl_cert_archive_location }}/cert.pem"
      checksum: sha1
      get_checksum: yes
    register: file_2

  - debug:
      var: file_1.stat.checksum

  - debug:
      var: file_2.stat.checksum

  - meta: end_play
    name: "The {{ ssl_cert_current_location }}/cert.pem and {{ ssl_cert_archive_location }}/cert.pem are identical"
    when: file_1.stat.checksum == file_2.stat.checksum

- hosts: target

  become: yes
  tasks:

    - meta: end_play
      when: file_1.stat.checksum == file_2.stat.checksum
    
    - name: Going through all targets
      shell: "ls"
      when: file_changed == "true"
