---
- hosts: all

  become: yes
  tasks:
    
    - name: "Check if ssl cert {{ ssl_cert_current }} has been renewed" 
      copy:
        src: {{ ssl_cert_archive }}
        dest: {{ ssl_cert_current }}
      check_mode: yes
      diff: yes
      register: file_changed
      msg: file_changed

    - name: "file has changed"
      when: file_changed == "true"
