---
- hosts: source

  become: yes
  tasks:

    - shell: diff {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}/cert.pem
      register: diff
      failed_when: diff.rc not in [ 0, 1 ]
  
    - debug:
      var: diff.stdout_lines
  
- hosts: target

  become: yes
  tasks:

    - meta: end_play
      when: file_1.stat.checksum == file_2.stat.checksum
    
    - name: Going through all targets
      shell: "ls"
      when: file_changed == "true"
