---
- hosts: source

  become: yes
  tasks:

    - name: "Comparing {{ ssl_cert_current_location }}/cert.pem with {{ ssl_cert_archive_location }}/cert.pem"
      shell: diff {{ ssl_cert_current_location }}/cert.pem {{ ssl_cert_archive_location }}/cert.pem
      register: diff
      failed_when: diff.rc not in [ 0, 1 ]

    - name: "The files have not changed"
      set_fact: 
        files_changed: "no"
      when: diff.stdout_lines == "[]"

    - name: "The files have changed"
      set_fact: 
        files_changed: "yes"
      when: diff.stdout_lines != "[]"
      
    - debug:
        var: diff.stdout_lines
  
- hosts: target

  become: yes
  tasks:

    - meta: end_play
      when: hostvars['192.168.10.102']['file_changed'] == "no"
    
    - name: Going through all targets
      shell: "ls"
      when: file_changed == "true"
